import {
  createHashRouter,
  createPanel,
  createRoot,
  createView,
  RoutesConfig,
} from '@vkontakte/vk-mini-apps-router';
import { RULES_PANELS } from './rules/routes';
import { rulesPath } from './rules/paths';

export const DEFAULT_ROOT = 'default_root';

export const DEFAULT_VIEW = 'default_view';

export const DEFAULT_VIEW_PANELS = {
  HOME: 'home',
  ACHIEVEMENTS: 'achievements',
  ACHIEVEMENTS_SHEET: 'achievements_sheet',
  INVENTORY: 'inventory',
  INVENTORY_SHEET: 'inventory_sheet',
  NAVIGATION: 'navigation',
  RULES: RULES_PANELS.HOME,
  RULES_REGISTRATION: RULES_PANELS.REGISTRATION,
  RULES_GAME: RULES_PANELS.GAME,
  RULES_REVARDS: RULES_PANELS.REVARDS,
  RULES_LD: RULES_PANELS.LD,
  RULES_ABILITIES: RULES_PANELS.ABILITIES,
  RULES_CYBORGS: RULES_PANELS.CYBORGS,
  RULES_DF: RULES_PANELS.DF,
  RULES_HAKI: RULES_PANELS.HAKI,
  RULES_SEIMEI: RULES_PANELS.SEIMEI,
  RULES_IOSORY: RULES_PANELS.IOSORY,
  RULES_RESTRICTIONS: RULES_PANELS.RESTRICTIONS,
  RULES_PIRATES: RULES_PANELS.PIRATES,
  RULES_RA: RULES_PANELS.RA,
  RULES_MARINE: RULES_PANELS.MARINE,
  RULES_MARINE_ISLAND_CONTROL: RULES_PANELS.MARINE_ISLAND_CONTROL,
  RULES_CP: RULES_PANELS.CP,
  RULES_EQUIPMENT: RULES_PANELS.EQUIPMENT,
  RULES_RACES: RULES_PANELS.RACES,
  RULES_FISHMANKARATE: RULES_PANELS.FISHMANKARATE,
  RULES_MERMAIDSTYLE: RULES_PANELS.MERMAIDSTYLE,
  RULES_POWERTABLET: RULES_PANELS.POWERTABLET,
  RULES_REBILD: RULES_PANELS.REBILD,
  RULES_CANON: RULES_PANELS.CANON,
  RULES_REQUIEM: RULES_PANELS.REQUIEM,
  RULES_REQUIEMQUESTS: RULES_PANELS.REQUIEMQUESTS,
  RULES_REQUIEMSHOP: RULES_PANELS.REQUIEMSHOP,
  RULES_REQUIEMWALLET: RULES_PANELS.REQUIEMWALLET,
  RULES_BOSSES: RULES_PANELS.BOSSES,
  SOUTH: 'south',
  WEST: 'west',
};

export const routes = RoutesConfig.create([
  createRoot(DEFAULT_ROOT, [
    createView(DEFAULT_VIEW, [
      createPanel(DEFAULT_VIEW_PANELS.HOME, '/', []),
      createPanel(DEFAULT_VIEW_PANELS.ACHIEVEMENTS, `/${DEFAULT_VIEW_PANELS.ACHIEVEMENTS}`, []),
      createPanel(
        DEFAULT_VIEW_PANELS.ACHIEVEMENTS_SHEET,
        `/${DEFAULT_VIEW_PANELS.ACHIEVEMENTS}/:sheetGid`,
        [],
        ['sheetGid'],
      ),
      createPanel(DEFAULT_VIEW_PANELS.INVENTORY, `/${DEFAULT_VIEW_PANELS.INVENTORY}`, []),
      createPanel(
        DEFAULT_VIEW_PANELS.INVENTORY_SHEET,
        `/${DEFAULT_VIEW_PANELS.INVENTORY}/:sheetGid`,
        [],
        ['sheetGid'],
      ),
      createPanel(DEFAULT_VIEW_PANELS.NAVIGATION, `/${DEFAULT_VIEW_PANELS.NAVIGATION}`, []),
      createPanel(RULES_PANELS.HOME, rulesPath(), []),
      createPanel(RULES_PANELS.REGISTRATION, rulesPath('registration'), []),
      createPanel(RULES_PANELS.GAME, rulesPath('game'), []),
      createPanel(RULES_PANELS.REVARDS, rulesPath('revards'), []),
      createPanel(RULES_PANELS.LD, rulesPath('ld'), []),
      createPanel(RULES_PANELS.ABILITIES, rulesPath('abilities'), []),
      createPanel(RULES_PANELS.CYBORGS, rulesPath('cyborgs'), []),
      createPanel(RULES_PANELS.DF, rulesPath('df'), []),
      createPanel(RULES_PANELS.HAKI, rulesPath('haki'), []),
      createPanel(RULES_PANELS.SEIMEI, rulesPath('seimei'), []),
      createPanel(RULES_PANELS.IOSORY, rulesPath('iosory'), []),
      createPanel(RULES_PANELS.RESTRICTIONS, rulesPath('restrictions'), []),
      createPanel(RULES_PANELS.PIRATES, rulesPath('pirates'), []),
      createPanel(RULES_PANELS.RA, rulesPath('ra'), []),
      createPanel(RULES_PANELS.MARINE, rulesPath('marine'), []),
      createPanel(RULES_PANELS.MARINE_ISLAND_CONTROL, rulesPath('marineislandcontrol'), []),
      createPanel(RULES_PANELS.CP, rulesPath('cp'), []),
      createPanel(RULES_PANELS.EQUIPMENT, rulesPath('equipment'), []),
      createPanel(RULES_PANELS.RACES, rulesPath('races'), []),
      createPanel(RULES_PANELS.FISHMANKARATE, rulesPath('fishmankarate'), []),
      createPanel(RULES_PANELS.MERMAIDSTYLE, rulesPath('mermaidstyle'), []),
      createPanel(RULES_PANELS.POWERTABLET, rulesPath('powertablet'), []),
      createPanel(RULES_PANELS.REBILD, rulesPath('rebild'), []),
      createPanel(RULES_PANELS.CANON, rulesPath('canon'), []),
      createPanel(RULES_PANELS.REQUIEM, rulesPath('requiem'), []),
      createPanel(RULES_PANELS.REQUIEMQUESTS, rulesPath('requiemquests'), []),
      createPanel(RULES_PANELS.REQUIEMSHOP, rulesPath('requiemshop'), []),
      createPanel(RULES_PANELS.REQUIEMWALLET, rulesPath('requiemwallet'), []),
      createPanel(RULES_PANELS.BOSSES, rulesPath('bosses'), []),
      createPanel(DEFAULT_VIEW_PANELS.SOUTH, `/${DEFAULT_VIEW_PANELS.SOUTH}`, []),
      createPanel(DEFAULT_VIEW_PANELS.WEST, `/${DEFAULT_VIEW_PANELS.WEST}`, []),
    ]),
  ]),
]);

export const router = createHashRouter(routes.getRoutes());
